---
title: "Twitter Data Collecting and Cleaning"
subtitle: "Homework 09"
author: "Jenifer M. Nemoda"
date: "04/29/2021"
output: html_document
---


```{r}
#recovering tweets from our chosen people: Boris Johnson and AOC
library(rtweet)

## select one or more twitter users to lookup
users <- c("BorisJohnson", "aoc")

## get users data
usr_df <- lookup_users(users)

## view users data
usr_df

## view tweet data for these users via tweets_data()
tweets_data(usr_df)

bj <- get_timeline("BorisJohnson",  n=3200)
aoc <- get_timeline("aoc", n=3200)
```


```{r}
library(dplyr)

#selecting only relevant variables ('select')
#selecting only 200 rows from each person (as in the class exercise)

bj %>%  filter(is_retweet=="FALSE") %>% 
  select("screen_name","text") %>%  #, "created_at"
  head(200) -> bj2

aoc %>%  filter(is_retweet=="FALSE") %>% 
  select("screen_name","text") %>%  #, "created_at"
  head(200) -> aoc2

#creating one file with tweets from both people
tweets_hw9 <- bind_rows(bj2,aoc2)

tweets_hw9 %>% mutate(id = row_number()) %>% 
  rename("author" = "screen_name", "status" = "text") -> tweets_hw9_v0.2

#write.csv(tweets_hw9_tidy, "~/V/penn/Spring2021/516/")
write.csv(tweets_hw9_v0.2, file = "tweets_hw9_tidy.csv")
```
